[project]
name = "falbe"
version = "0.1.0"
dependencies = ["pandas"] # Add your runtime dependencies here

[build-system]
requires = ["setuptools >= 70"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]
dev = ["pyright"]